import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.css";
import StyledJsxRegistry from "../lib/styled-components/registry";
import Image from "next/image";

import LogoImage from "../../public/task-list-logo.png"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledJsxRegistry>
          <nav className="flex justify-between items-center bg-backgroundColor text-white p-5">
            <Image
              src={LogoImage}
              alt="Logo Image"
              width={50}
              height={50}
            />
            <p>Another text here</p>
          </nav>
          <main>{children}</main>
        </StyledJsxRegistry>
      </body>
    </html>
  );
}
