import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.css";
import StyledJsxRegistry from "../lib/styled-components/registry";
import Image from "next/image";

import LogoImage from "../../public/task-list-logo.png"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title:{
    template: "Task List - %s",
    default: "Task List"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Classes no body para que eu consiga fazer o main ocupar o espaço necessário para preencher a tela inteira */}
      <body className={`${inter.className} min-h-screen flex flex-col`}>
        <StyledJsxRegistry>
          <nav className="flex justify-center bg-background-color text-white p-5 md:justify-start">
            <Image
              src={LogoImage}
              alt="Logo Image"
              width={50}
              height={50}
            />
            {/* <p>Another text here</p> */}
          </nav>
          <main className="flex flex-col flex-1">{children}</main>
        </StyledJsxRegistry>
      </body>
    </html>
  );
}
